dist: xenial
language: python
python:
 - "3.7"
  
install:
 - pip3 install pycodestyle
 - cd validator
 - pip3 install -r requirements.txt
 - npm install -g ajv-cli
 - docker run --name mongodb -d mongo:3.6
 - docker run -d --name orion1 --link mongodb:mongodb -p 1026:1026 fiware/orion -dbhost mongodb
 
script:
  # stop the build if there are Python syntax errors, PEP8 violations, undefined names
 - pycodestyle ./ --max-line-length=127 --show-source --statistics
 - python3 -m unittest test/validator_test.py
  
notifications:
  on_success: change
  on_failure: always
